# May be either NONE, FILE, POSTGRESQL or MYSQL
storage-type: NONE

file:
  expire:

postgresql:
  host: localhost
  database: testing
  user: user
  password: password

mysql:
  host: localhost
  database: testing
  user: user
  password: password
