# Determines how the Intave storage data is saved. Options (choose one):
# - NONE (storage data is not saved)
# - FILE (storage data is saved in the .intave folder)
# - POSTGRESQL (storage data is stored in a Postgresql DBMS)
# - MARIADB (storage data is stored in a MariaDB DBMS)
# - MYSQL (storage data is stored in a MySQL DBMS)
# - MONGODB (storage data is stored in a MongoDB DBMS)
storage-type: NONE

# Configuration for the FILE storage type. Used only if the storage type is set
# to FILE.
# Intave Storage will create a directory called 'Storage' in the same .intave
# folder Intave uses and store data files there.
file:
  # How many days should we keep storage data after the player's last connection
  # date?
  # Minimum: 1
  # Recommended: 30
  # Maximum (no expiration / file deletion): -1
  expire: 30

# Configuration for the POSTGRESQL storage type. Used only if the storage type
# is set to POSTGRESQL.
# Intave Storage will create a table called 'intave_storage' (if it does not
# exist in the DBMS) and only read/write from that table.
postgresql:
  # Which host is the DBMS at?
  # Example: localhost
  # Example: localhost:12345
  host: localhost
  # Which database should we connect to?
  database: testing
  # Which user should we use to connect to the DBMS?
  user: user
  # Which password should we use to connect to the DBMS?
  password: password
  # How many days should we keep storage data after the player's last connection
  # date?
  # Minimum: 1
  # Recommended: 30
  # Maximum (no expiration / entry deletion): -1
  expire: 30

# Configuration for the MARIADB storage type. Used only if the storage type is
# set to MARIADB.
# Intave Storage will create a table called 'intave_storage' (if it does not
# exist in the DBMS) and only read/write from that table.
mariadb:
  # Which host is the DBMS at?
  # Example: localhost
  # Example: localhost:12345
  host: localhost
  # Which database should we connect to?
  database: testing
  # Which user should we use to connect to the DBMS?
  user: user
  # Which password should we use to connect to the DBMS?
  password: password
  # How many days should we keep storage data after the player's last connection
  # date?
  # Minimum: 1
  # Recommended: 30
  # Maximum (no expiration / entry deletion): -1
  expire: 30

# Configuration for the MYSQL storage type. Used only if the storage type is set
# to MYSQL.
# Intave Storage will create a table called 'intave_storage' (if it does not
# exist in the DBMS) and only read/write from that table.
mysql:
  # Which host is the DBMS at?
  # Example: localhost
  # Example: localhost:12345
  host: localhost
  # Which database should we connect to?
  database: testing
  # Which user should we use to connect to the DBMS?
  user: user
  # Which password should we use to connect to the DBMS?
  password: password
  # How many days should we keep storage data after the player's last connection
  # date?
  # Minimum: 1
  # Recommended: 30
  # Maximum (no expiration / entry deletion): -1
  expire: 30

# Configuration for the MONGODB storage type. Used only if the storage type is set
# to MONGODB.
# Intave Storage will create a database and collection "storage" with the supplied name (if it does not
# exist in the DBMS) and only read/write from that database and collection "storage".
mongodb:
  # Which host is the DBMS at?
  # Example: localhost
  # Example: localhost:12345
  host: localhost
  # Which database should we connect to?
  database: testing
  # Should we use a username and password to connect to the DBMS?
  authorization: true
  # Which user should we use to connect to the DBMS?
  user: user
  # Which password should we use to connect to the DBMS?
  password: password
  # Which default database does the user have assigned?
  defaultdb: admin
  # How many days should we keep storage data after the player's last connection
  # date?
  # Minimum: 1
  # Recommended: 30
  # Maximum (no expiration / entry deletion): -1
  expire: 30
