name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build
          gradle-version: wrapper
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: intave-storage
          path: ./build/libs/intavestorage-*-*.jar
